//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bisutti.Brigada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-05")]
        public global::System.DateTime Inicio {
            get {
                return ((global::System.DateTime)(this["Inicio"]));
            }
            set {
                this["Inicio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-31")]
        public global::System.DateTime Termino {
            get {
                return ((global::System.DateTime)(this["Termino"]));
            }
            set {
                this["Termino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eventos de {0} até {1}")]
        public string BrigadaSubject {
            get {
                return ((string)(this["BrigadaSubject"]));
            }
            set {
                this["BrigadaSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1,2,3,4,5,6")]
        public string EventosExcelOrder {
            get {
                return ((string)(this["EventosExcelOrder"]));
            }
            set {
                this["EventosExcelOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1,2,3,4,5,6,7,9")]
        public string BrigadaExcelOrder {
            get {
                return ((string)(this["BrigadaExcelOrder"]));
            }
            set {
                this["BrigadaExcelOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rafael.ravena@gmail.com")]
        public string DevelopersEmail {
            get {
                return ((string)(this["DevelopersEmail"]));
            }
            set {
                this["DevelopersEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eventos da Semana ({0} a {1})")]
        public string ProducaoSubject {
            get {
                return ((string)(this["ProducaoSubject"]));
            }
            set {
                this["ProducaoSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveLastScreen {
            get {
                return ((bool)(this["SaveLastScreen"]));
            }
            set {
                this["SaveLastScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendAutomatically {
            get {
                return ((bool)(this["SendAutomatically"]));
            }
            set {
                this["SendAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Arquivos\\Brigada.htm")]
        public string BrigadaEmailFile {
            get {
                return ((string)(this["BrigadaEmailFile"]));
            }
            set {
                this["BrigadaEmailFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Arquivos\\Producao.htm")]
        public string ProducaoEmailFile {
            get {
                return ((string)(this["ProducaoEmailFile"]));
            }
            set {
                this["ProducaoEmailFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuracoes")]
        public string LastScreen {
            get {
                return ((string)(this["LastScreen"]));
            }
            set {
                this["LastScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Arquivos\\excel.xlsx")]
        public string LastExcelFile {
            get {
                return ((string)(this["LastExcelFile"]));
            }
            set {
                this["LastExcelFile"] = value;
            }
        }
    }
}
